Grasping at ways to get libapr loaded for JNI.  Some of these changes may be reverted at a later date, but including them for posterity now.
* subversion/bindings/swig/java/org/tigris/subversion/util/NativeResources.java
  getInstance(): Additional JavaDoc.

  initialize(): Added JavaDoc about possible UnsatisfiedLinkErrors (a
    variety of LinkageError). Also, try explicitly loading APR to
    avoid this "symbol not found" exception for apr_initialize().
    Haven't got this working yet, and not sure that it's even the
    Right direction.


* subversion/bindings/swig/swigutil_java.c
  (svn_swig_java__libtool_hack): Reference apr_initialize() in an
    unused function as a completely hackish means of including an
    undefined reference to apr_initialize in libsvn_swig_java's .so
    file.  This seems more like the Right direction, as it is along
    the lines of what Apache httpd 2 does with build/make_exports.awk
    to hack around libtool (thanks to Justin for the pointer to that).