Fix the swig-py examples.
When trying to run the get-location-segments.py, it throws:

    TypeError: Unexpected NULL parent pool on proxy object

Somehow, the "_parent_pool" property wasn't initialized on the context.
Not sure how this works, but creating a context using
client.svn_client_create_context() instead of client.ctx_t() (which
subversion/bindings/swig/python/tests/pool.py also does) fixes this
error and makes the example work again.

* tools/examples/get-location-segments.py
  (main): Use client.svn_client_create_context instead of client.ctx_t.

* tools/examples/SvnCLBrowse
  (SvnCLBrowse.__init__): Same.

Patch by: Matthijs Kooijman <matthijs@stdin.nl>
(SvnCLBrowse part by me)