Merge r9720,r9727 and remove from STATUS.
Fix problem with javahl bindings which triggers a
java.lang.NoSuchMethodError exception and problems where the callback
from C calls the wrong java method.
The second problem can lead to a crash of the java virtual machine.
     
Approved by: +1: pmayweg; +0: breser